### ISSUE TITLE
Ошибка инициализации UIColor

### ISSUE THREAD

**Issue by ghost** [HandsAppDevelopment/HandsAppUI#1]
![Снимок экрана 2019-11-08 в 17 09 41](https://user-images.githubusercontent.com/53041799/68482432-a65a6980-024a-11ea-883c-99e43f0f2b31.png)

Инициализация возможна только через rgb, а не через hex

**Comment by Mol0ko** [comment]
Нужно сделать `extension UIColor`  публичным

**Comment by Mol0ko** [comment]
fixed
